services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5173:5173"
    volumes:
      - .:/frontend
      - "/frontend/node_modules"