name: Lint Code

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: ./frontend/package.json
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: ./frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./frontend

      - name: Run ESLint
        run: pnpm lint
        working-directory: ./frontend

  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      # Uncomment this if dependency installation is needed in the future
      # - name: Install dependencies
      #   run: pip install -r requirements.txt
      #   working-directory: ./backend

      - name: Install ruff
        run: pip install ruff
        working-directory: ./backend

      - name: Run ruff linter
        run: ruff check .
        working-directory: ./backend
